const employees = [
  { id: 12, name: "Chris" },
  { id: 13, name: "Day" },
  { id: 1, name: "Mook" },
  { id: 2, name: "Rose" },
  { id: 3, name: "Moss" },
  { id: 4, name: "Bella" },
  { id: 6, name: "Sky" },
  { id: 5, name: "Lucus" },
  { id: 7, name: "Hut" },
  { id: 8, name: "Christian" },
  { id: 9, name: "Min" },
  { id: 10, name: "Yok" },
  { id: 11, name: "Ethan" },
];

export default employees;

// { id: 12, name: "Chris" },
// { id: 13, name: "Day" },
// { id: 1, name: "Mook" },
// { id: 2, name: "Rose" },
// { id: 3, name: "Moss" },
// { id: 4, name: "Bella" },
// { id: 6, name: "Sky" },
// { id: 5, name: "Lucus" },
// { id: 7, name: "Hut" },
// { id: 8, name: "Christian" },
// { id: 9, name: "Min" },
// { id: 10, name: "Yok" },
// { id: 11, name: "Ethan" },
